//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int id { get; set; }
        public int ClientId { get; set; }
        public string PhoneNumber { get; set; }
        public int PhoneTypeId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
